const DISPOSABLE_DOMAINS = new Set<string>([
  '0-mail.com', '0815.ru', '10mail.org', '10minutemail.com', '10minutemail.net',
  '10minutemail.de', '10minutemail.co.uk', '20mail.it', '20minutemail.com', '2prong.com',
  '30minutemail.com', '33mail.com', '3d-painting.com', '4warding.com', '4warding.net',
  '60minutemail.com', '675hosting.com', '6paq.com', '7tags.com', '99experts.com',
  'aaaaaaaaaaaaa.com', 'abyssmail.com', 'afrobacon.com', 'ajaxapp.net', 'amilegit.com',
  'anonbox.net', 'anonmail.top', 'anonymbox.com', 'antichef.com', 'antichef.net',
  'antispam.de', 'armyspy.com', 'autorambler.ru', 'baxomale.ht.cx', 'beefmilk.com',
  'binkmail.com', 'bio-muesli.net', 'bobmail.info', 'bofthew.com', 'boun.cr',
  'bouncr.com', 'breakthru.com', 'brefmail.com', 'bsnow.net', 'bspamfree.org',
  'bugmenot.com', 'bumpymail.com', 'burnermail.io', 'burstmail.info', 'buyusedlibrarybooks.org',
  'byom.de', 'casualdx.com', 'centermail.com', 'centermail.net', 'chammy.info',
  'chogmail.com', 'choicemail1.com', 'cool.fr.nf', 'correo.blogos.net', 'cosmorph.com',
  'courriel.fr.nf', 'courrieltemporaire.com', 'crazymailing.com', 'crymail2.com', 'cubiclink.com',
  'curryworld.de', 'cust.in', 'dacoolest.com', 'dandikmail.com', 'dayrep.com',
  'deadaddress.com', 'deagot.com', 'dealja.com', 'despam.it', 'devnullmail.com',
  'dharmatel.net', 'digitalsanctuary.com', 'dingbone.com', 'discardmail.com', 'discardmail.de',
  'disposableaddress.com', 'disposableemailaddresses.com', 'disposableinbox.com', 'dispostable.com', 'dodgeit.com',
  'dodgit.com', 'dontreg.com', 'dontsendmespam.de', 'drdrb.net', 'dump-email.info',
  'dumpandjunk.com', 'dumpmail.de', 'dumpyemail.com', 'duskmail.com', 'e4ward.com',
  'easytrashmail.com', 'einrot.com', 'eintagsmail.de', 'email60.com', 'emailgo.de',
  'emailias.com', 'emailigo.de', 'emailinfive.com', 'emaillime.com', 'emailmiser.com',
  'emailondeck.com', 'emailproxsy.com', 'emailsensei.com', 'emailtemporanea.com', 'emailtemporanea.net',
  'emailtemporario.com.br', 'emailthe.net', 'emailtmp.com', 'emailto.de', 'emailwarden.com',
  'emailx.at.hm', 'emailxfer.com', 'emeil.in', 'emz.net', 'ephemeral.email',
  'etranquil.com', 'etranquil.net', 'evopo.com', 'explodemail.com', 'fakeinbox.com',
  'fakeinformation.com', 'fakemailgenerator.com', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com',
  'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com',
  'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com', 'fightallspam.com', 'filzmail.com',
  'fizmail.com', 'fleckens.hu', 'frapmail.com', 'fudgerub.com', 'fuirio.com',
  'garliclife.com', 'get1mail.com', 'get2mail.fr', 'getairmail.com', 'getmails.eu',
  'getonemail.com', 'getonemail.net', 'ghosttexter.de', 'girlsundertheinfluence.com', 'gishpuppy.com',
  'gmial.com', 'gotmail.com', 'gotmail.net', 'gotmail.org', 'gotti.otherinbox.com',
  'great-host.in', 'grr.la', 'gsrv.co.uk', 'guerillamail.biz', 'guerillamail.com',
  'guerillamail.net', 'guerillamail.org', 'guerillamailblock.com', 'guerrillamail.com', 'guerrillamail.de',
  'guerrillamail.info', 'guerrillamail.net', 'guerrillamail.org', 'guerrillamailblock.com', 'haltospam.com',
  'harakirimail.com', 'hatespam.org', 'hidzz.com', 'hmamail.com', 'hochsitze.com',
  'hopemail.biz', 'hotpop.com', 'hulapla.de', 'ieatspam.eu', 'ieatspam.info',
  'ihateyoualot.info', 'iheartspam.org', 'imails.info', 'incognitomail.net', 'incognitomail.org',
  'inboxalias.com', 'inboxbear.com', 'inboxclean.com', 'inboxclean.org', 'inboxkitten.com',
  'incognitomail.com', 'instant-mail.de', 'ip6.li', 'irish2me.com', 'iwi.net',
  'jetable.fr.nf', 'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com',
  'jsrsolutions.com', 'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com',
  'killmail.net', 'kir.ch.tc', 'klassmaster.com', 'klzlk.com', 'kulturbetrieb.info',
  'kurzepost.de', 'lawlita.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com', 'lol.ovpn.to', 'lookugly.com', 'lopl.co.cc',
  'lortemail.dk', 'lr78.com', 'lroid.com', 'lukop.dk', 'm21.cc',
  'maboard.com', 'mail-filter.com', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net',
  'mail4trash.com', 'mailbidon.com', 'mailblocks.com', 'mailcatch.com', 'maildrop.cc',
  'maildx.com', 'maileater.com', 'mailexpire.com', 'mailfa.tk', 'mailforspam.com',
  'mailfreeonline.com', 'mailguard.me', 'mailimate.com', 'mailin8r.com', 'mailinater.com',
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com', 'mailincubator.com',
  'mailismagic.com', 'mailme.lv', 'mailmetrash.com', 'mailmoat.com', 'mailms.com',
  'mailnator.com', 'mailnesia.com', 'mailnull.com', 'mailpick.biz', 'mailrock.biz',
  'mailshell.com', 'mailsiphon.com', 'mailslapping.com', 'mailtemp.info', 'mailtome.de',
  'mailtothis.com', 'mailtrash.net', 'mailtv.net', 'mailtv.tv', 'mailzilla.com',
  'mailzilla.org', 'makemetheking.com', 'manybrain.com', 'mbx.cc', 'mega.zik.dj',
  'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de', 'mierdamail.com', 'mintemail.com',
  'misterpinball.de', 'mneon.com', 'moburl.com', 'mohmal.com', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf', 'msa.minsmail.com', 'mt2009.com', 'mx0.wwwnew.eu',
  'mycard.net.ua', 'mycleaninbox.net', 'myemailboxy.com', 'mymail-in.net', 'mypartyclip.de',
  'myphantomemail.com', 'mysamp.de', 'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
  'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net', 'netmails.com',
  'netmails.net', 'neverbox.com', 'no-spam.ws', 'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.xl.cx', 'nomail2me.com', 'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net', 'notmailinator.com', 'nowmymail.com', 'nurfuerspam.de',
  'nus.edu.sg', 'objectmail.com', 'obobbo.com', 'odaymail.com', 'oneoffemail.com',
  'onewaymail.com', 'onlatedotcom.info', 'online.ms', 'oopi.org', 'ordinaryamerican.net',
  'otherinbox.com', 'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pjjkp.com',
  'plexolan.de', 'poczta.onet.pl', 'politikerclub.de', 'poofy.org', 'pookmail.com',
  'privacy.net', 'privatdemail.net', 'privymail.de', 'proxymail.eu', 'prtnx.com',
  'putthisinyourspamdatabase.com', 'pwrby.com', 'quickinbox.com', 'rcpt.at', 'reallymymail.com',
  'recode.me', 'recursor.net', 'reliable-mail.com', 'rhyta.com', 'rmqkr.net',
  'royal.net', 'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net',
  'safersignup.de', 'safetymail.info', 'safetypost.de', 'saynotospams.com', 'schafmail.de',
  'selfdestructingmail.com', 'sendspamhere.com', 'sharklasers.com', 'shieldedmail.com', 'shiftmail.com',
  'shitmail.me', 'shitware.nl', 'shmeriously.com', 'shortmail.net', 'sibmail.com',
  'sinnlos-mail.de', 'slaskpost.se', 'slipry.net', 'slopsbox.com', 'smashmail.de',
  'smellfear.com', 'snakemail.com', 'sneakemail.com', 'snkmail.com', 'sofimail.com',
  'sofort-mail.de', 'sogetthis.com', 'soodonims.com', 'spam.la', 'spam.su',
  'spam4.me', 'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.us', 'spamcannon.com',
  'spamcannon.net', 'spamcero.com', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamex.com', 'spamfree.eu', 'spamfree24.com',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com',
  'spamhereplease.com', 'spamhole.com', 'spamify.com', 'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de', 'spammotel.com', 'spamobox.com', 'spamoff.de',
  'spamslicer.com', 'spamspot.com', 'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com',
  'speed.1s.fr', 'spoofmail.de', 'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info', 'tafmail.com',
  'talkinator.com', 'tagyourself.com', 'teewars.org', 'teleworm.com', 'teleworm.us',
  'temp-mail.com', 'temp-mail.org', 'temp-mail.ru', 'tempail.com', 'tempemail.biz',
  'tempemail.com', 'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com', 'tempmail.eu',
  'tempmail.it', 'tempmail2.com', 'tempmaildemand.com', 'tempmailer.com', 'tempmailer.de',
  'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br', 'temporaryemail.net', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com', 'tempthe.net', 'tempymail.com', 'thanksnospam.info',
  'thankyou2010.com', 'thecloudindex.com', 'thelimestones.com', 'thisisnotmyrealemail.com', 'thismail.net',
  'throwawayemailaddress.com', 'tilien.com', 'tittbit.in', 'tizi.com', 'tmail.ws',
  'tmailinator.com', 'toiea.com', 'tokem.co', 'toomail.biz', 'topranklist.de',
  'tradermail.info', 'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash2009.com', 'trashemail.de', 'trashinbox.com', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.ws',
  'trashmailer.com', 'trashymail.com', 'trashymail.net', 'trillianpro.com', 'turual.com',
  'twinmail.de', 'twoweirdtricks.com', 'tyldd.com', 'uggsrock.com', 'umail.net',
  'upliftnow.com', 'uplipht.com', 'uroid.com', 'venompen.com', 'veryrealemail.com',
  'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org', 'vpn.st',
  'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me', 'webm4il.info',
  'wegwerfadresse.de', 'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org', 'wh4f.org', 'whatpaas.com', 'whyspam.me', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info', 'wronghead.com', 'wuzup.net', 'wuzupmail.net',
  'www.e4ward.com', 'www.gishpuppy.com', 'www.mailinator.com', 'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xents.com', 'xmaily.com', 'xoxy.net', 'yapped.net',
  'yeah.net', 'yep.it', 'yogamaven.com', 'yopmail.com', 'yopmail.fr',
  'yopmail.net', 'youmailr.com', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org', 'yuurok.com',
  'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de', 'zetmail.com',
  'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info', 'zxcv.com',
  'zxcvbnm.com', 'zzz.com',
])

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf('@')
  if (at === -1) return false
  const domain = email.slice(at + 1).trim().toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}

export function getDisposableDomains(): ReadonlySet<string> {
  return DISPOSABLE_DOMAINS
}
